<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0c72e9924da196c5dbc54fc8f4363cce
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Database\\' => 9,
        ),
        'C' => 
        array (
            'Controllers\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Database\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Database',
        ),
        'Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Controllers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0c72e9924da196c5dbc54fc8f4363cce::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0c72e9924da196c5dbc54fc8f4363cce::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0c72e9924da196c5dbc54fc8f4363cce::$classMap;

        }, null, ClassLoader::class);
    }
}
